import "dotenv/config";
import { randomUUID } from "node:crypto";
import { db } from "../src/db";
import { legacyPlayerCareerStats } from "../src/db/schema";

const data = [
  {
    playerName: "Christian Krause",
    points: 306,
    goals: 186,
    minutesPerGoal: 51,
    hattricks: 25,
    doublepacks: 33,
    assists: 120,
    assistsPerGame: 1.14,
    games: 105,
    winsRatio: 46.67,
    lossesRatio: 39.05,
    ownGoals: 0,
  },
  {
    playerName: "Christian Junge",
    points: 211,
    goals: 132,
    minutesPerGoal: 79,
    hattricks: 15,
    doublepacks: 19,
    assists: 79,
    assistsPerGame: 0.68,
    games: 116,
    winsRatio: 43.97,
    lossesRatio: 42.24,
    ownGoals: 3,
  },
  {
    playerName: "Lars Finck",
    points: 192,
    goals: 108,
    minutesPerGoal: 86,
    hattricks: 9,
    doublepacks: 22,
    assists: 84,
    assistsPerGame: 0.82,
    games: 103,
    winsRatio: 42.72,
    lossesRatio: 42.72,
    ownGoals: 0,
  },
  {
    playerName: "Lars Follmann",
    points: 191,
    goals: 121,
    minutesPerGoal: 81,
    hattricks: 14,
    doublepacks: 21,
    assists: 70,
    assistsPerGame: 0.64,
    games: 109,
    winsRatio: 38.53,
    lossesRatio: 46.79,
    ownGoals: 0,
  },
  {
    playerName: "Michael Blümig",
    points: 189,
    goals: 119,
    minutesPerGoal: 87,
    hattricks: 12,
    doublepacks: 23,
    assists: 70,
    assistsPerGame: 0.61,
    games: 115,
    winsRatio: 40.0,
    lossesRatio: 46.96,
    ownGoals: 0,
  },
  {
    playerName: "Jari Gonzales",
    points: 145,
    goals: 66,
    minutesPerGoal: 135,
    hattricks: 5,
    doublepacks: 7,
    assists: 79,
    assistsPerGame: 0.8,
    games: 99,
    winsRatio: 48.48,
    lossesRatio: 38.38,
    ownGoals: 1,
  },
  {
    playerName: "Sven Lehmann",
    points: 131,
    goals: 71,
    minutesPerGoal: 117,
    hattricks: 6,
    doublepacks: 18,
    assists: 60,
    assistsPerGame: 0.65,
    games: 92,
    winsRatio: 39.13,
    lossesRatio: 47.83,
    ownGoals: 0,
  },
  {
    playerName: "Björn Steinhardt",
    points: 123,
    goals: 39,
    minutesPerGoal: 254,
    hattricks: 2,
    doublepacks: 4,
    assists: 84,
    assistsPerGame: 0.76,
    games: 110,
    winsRatio: 50.91,
    lossesRatio: 35.45,
    ownGoals: 3,
  },
  {
    playerName: "Norbert Riebesehl",
    points: 110,
    goals: 75,
    minutesPerGoal: 82,
    hattricks: 10,
    doublepacks: 9,
    assists: 35,
    assistsPerGame: 0.51,
    games: 68,
    winsRatio: 45.59,
    lossesRatio: 36.76,
    ownGoals: 0,
  },
  {
    playerName: "Andreas Weseloh",
    points: 90,
    goals: 66,
    minutesPerGoal: 89,
    hattricks: 5,
    doublepacks: 15,
    assists: 24,
    assistsPerGame: 0.37,
    games: 65,
    winsRatio: 47.69,
    lossesRatio: 38.46,
    ownGoals: 1,
  },
  {
    playerName: "Michael Schönherr",
    points: 85,
    goals: 50,
    minutesPerGoal: 128,
    hattricks: 2,
    doublepacks: 9,
    assists: 35,
    assistsPerGame: 0.49,
    games: 71,
    winsRatio: 45.07,
    lossesRatio: 40.85,
    ownGoals: 1,
  },
  {
    playerName: "Till Romainschick",
    points: 81,
    goals: 38,
    minutesPerGoal: 126,
    hattricks: 2,
    doublepacks: 6,
    assists: 43,
    assistsPerGame: 0.81,
    games: 53,
    winsRatio: 43.4,
    lossesRatio: 39.62,
    ownGoals: 0,
  },
  {
    playerName: "Stephan Ebel",
    points: 76,
    goals: 49,
    minutesPerGoal: 204,
    hattricks: 2,
    doublepacks: 8,
    assists: 27,
    assistsPerGame: 0.24,
    games: 111,
    winsRatio: 39.64,
    lossesRatio: 46.85,
    ownGoals: 2,
  },
  {
    playerName: "Jens Mergenthal",
    points: 73,
    goals: 32,
    minutesPerGoal: 160,
    hattricks: 0,
    doublepacks: 7,
    assists: 41,
    assistsPerGame: 0.72,
    games: 57,
    winsRatio: 52.63,
    lossesRatio: 31.58,
    ownGoals: 1,
  },
  {
    playerName: "Jürgen Magull",
    points: 66,
    goals: 45,
    minutesPerGoal: 58,
    hattricks: 7,
    doublepacks: 8,
    assists: 21,
    assistsPerGame: 0.72,
    games: 29,
    winsRatio: 34.48,
    lossesRatio: 51.72,
    ownGoals: 0,
  },
  {
    playerName: "Florian Wiards",
    points: 60,
    goals: 32,
    minutesPerGoal: 155,
    hattricks: 4,
    doublepacks: 1,
    assists: 28,
    assistsPerGame: 0.51,
    games: 55,
    winsRatio: 30.91,
    lossesRatio: 49.09,
    ownGoals: 2,
  },
  {
    playerName: "Christian Bartz",
    points: 49,
    goals: 29,
    minutesPerGoal: 267,
    hattricks: 0,
    doublepacks: 7,
    assists: 20,
    assistsPerGame: 0.23,
    games: 86,
    winsRatio: 36.05,
    lossesRatio: 46.51,
    ownGoals: 2,
  },
  {
    playerName: "Olaf Steinitz",
    points: 48,
    goals: 25,
    minutesPerGoal: 346,
    hattricks: 0,
    doublepacks: 4,
    assists: 23,
    assistsPerGame: 0.24,
    games: 96,
    winsRatio: 51.04,
    lossesRatio: 32.29,
    ownGoals: 2,
  },
  {
    playerName: "Felix Kroppenstedt",
    points: 40,
    goals: 23,
    minutesPerGoal: 223,
    hattricks: 2,
    doublepacks: 3,
    assists: 17,
    assistsPerGame: 0.3,
    games: 57,
    winsRatio: 47.37,
    lossesRatio: 31.58,
    ownGoals: 1,
  },
  {
    playerName: "Christian Stille",
    points: 22,
    goals: 7,
    minutesPerGoal: 1440,
    hattricks: 0,
    doublepacks: 2,
    assists: 15,
    assistsPerGame: 0.13,
    games: 112,
    winsRatio: 46.43,
    lossesRatio: 40.18,
    ownGoals: 5,
  },
  {
    playerName: "Arndt Püschel",
    points: 21,
    goals: 12,
    minutesPerGoal: 210,
    hattricks: 0,
    doublepacks: 3,
    assists: 9,
    assistsPerGame: 0.32,
    games: 28,
    winsRatio: 42.86,
    lossesRatio: 42.86,
    ownGoals: 1,
  },
  {
    playerName: "Marvin Duda",
    points: 17,
    goals: 4,
    minutesPerGoal: 1935,
    hattricks: 0,
    doublepacks: 0,
    assists: 13,
    assistsPerGame: 0.15,
    games: 86,
    winsRatio: 37.21,
    lossesRatio: 47.67,
    ownGoals: 0,
  },
  {
    playerName: "Lars Flemke",
    points: 16,
    goals: 11,
    minutesPerGoal: 131,
    hattricks: 1,
    doublepacks: 3,
    assists: 5,
    assistsPerGame: 0.31,
    games: 16,
    winsRatio: 50.0,
    lossesRatio: 31.25,
    ownGoals: 0,
  },
  {
    playerName: "Torsten Krüger",
    points: 16,
    goals: 5,
    minutesPerGoal: 2034,
    hattricks: 0,
    doublepacks: 0,
    assists: 11,
    assistsPerGame: 0.1,
    games: 113,
    winsRatio: 45.13,
    lossesRatio: 38.05,
    ownGoals: 0,
  },
  {
    playerName: "Jörg Paßlack",
    points: 15,
    goals: 3,
    minutesPerGoal: 1860,
    hattricks: 0,
    doublepacks: 1,
    assists: 12,
    assistsPerGame: 0.19,
    games: 62,
    winsRatio: 45.16,
    lossesRatio: 40.32,
    ownGoals: 2,
  },
  {
    playerName: "Tim Breckwoldt",
    points: 15,
    goals: 4,
    minutesPerGoal: 1260,
    hattricks: 0,
    doublepacks: 1,
    assists: 11,
    assistsPerGame: 0.2,
    games: 56,
    winsRatio: 46.43,
    lossesRatio: 33.93,
    ownGoals: 1,
  },
  {
    playerName: "Wolfgang Hübsch",
    points: 15,
    goals: 5,
    minutesPerGoal: 1422,
    hattricks: 0,
    doublepacks: 2,
    assists: 10,
    assistsPerGame: 0.13,
    games: 79,
    winsRatio: 39.24,
    lossesRatio: 46.84,
    ownGoals: 4,
  },
  {
    playerName: "Eduard Rosenkranz",
    points: 15,
    goals: 10,
    minutesPerGoal: 63,
    hattricks: 1,
    doublepacks: 3,
    assists: 5,
    assistsPerGame: 0.71,
    games: 7,
    winsRatio: 42.86,
    lossesRatio: 42.86,
    ownGoals: 0,
  },
  {
    playerName: "Kiri Papouloglou",
    points: 14,
    goals: 8,
    minutesPerGoal: 518,
    hattricks: 1,
    doublepacks: 0,
    assists: 6,
    assistsPerGame: 0.13,
    games: 46,
    winsRatio: 39.13,
    lossesRatio: 43.48,
    ownGoals: 0,
  },
  {
    playerName: "Marcus Schünzel",
    points: 14,
    goals: 2,
    minutesPerGoal: 4050,
    hattricks: 0,
    doublepacks: 0,
    assists: 12,
    assistsPerGame: 0.13,
    games: 90,
    winsRatio: 34.44,
    lossesRatio: 48.89,
    ownGoals: 1,
  },
  {
    playerName: "Bjarne Adam",
    points: 12,
    goals: 2,
    minutesPerGoal: 2475,
    hattricks: 0,
    doublepacks: 0,
    assists: 10,
    assistsPerGame: 0.18,
    games: 55,
    winsRatio: 43.64,
    lossesRatio: 40.0,
    ownGoals: 1,
  },
  {
    playerName: "Carsten Warratz",
    points: 8,
    goals: 3,
    minutesPerGoal: 1320,
    hattricks: 0,
    doublepacks: 1,
    assists: 5,
    assistsPerGame: 0.11,
    games: 44,
    winsRatio: 34.09,
    lossesRatio: 52.27,
    ownGoals: 1,
  },
  {
    playerName: "Thomas Ullrich",
    points: 3,
    goals: 1,
    minutesPerGoal: 1980,
    hattricks: 0,
    doublepacks: 0,
    assists: 2,
    assistsPerGame: 0.09,
    games: 22,
    winsRatio: 36.36,
    lossesRatio: 63.64,
    ownGoals: 0,
  },
  {
    playerName: "Bernd Wünsche",
    points: 3,
    goals: 1,
    minutesPerGoal: 5490,
    hattricks: 0,
    doublepacks: 0,
    assists: 2,
    assistsPerGame: 0.03,
    games: 61,
    winsRatio: 37.7,
    lossesRatio: 47.54,
    ownGoals: 0,
  },
  {
    playerName: "Oliver Bethke",
    points: 2,
    goals: 0,
    minutesPerGoal: 0,
    hattricks: 0,
    doublepacks: 0,
    assists: 2,
    assistsPerGame: 0.67,
    games: 3,
    winsRatio: 33.33,
    lossesRatio: 33.33,
    ownGoals: 1,
  },
  {
    playerName: "Roland Mielke",
    points: 1,
    goals: 0,
    minutesPerGoal: 0,
    hattricks: 0,
    doublepacks: 0,
    assists: 1,
    assistsPerGame: 0.04,
    games: 25,
    winsRatio: 32.0,
    lossesRatio: 48.0,
    ownGoals: 0,
  },
  {
    playerName: "Peter Brökelmann",
    points: 1,
    goals: 0,
    minutesPerGoal: 0,
    hattricks: 0,
    doublepacks: 0,
    assists: 1,
    assistsPerGame: 0.02,
    games: 43,
    winsRatio: 34.88,
    lossesRatio: 44.19,
    ownGoals: 0,
  },
  {
    playerName: "Uwe Spiekermann",
    points: 0,
    goals: 0,
    minutesPerGoal: 0,
    hattricks: 0,
    doublepacks: 0,
    assists: 0,
    assistsPerGame: 0.0,
    games: 78,
    winsRatio: 29.49,
    lossesRatio: 53.85,
    ownGoals: 0,
  },
];

async function main() {
  console.log("[start] Seeding legacy career stats...");

  const rows = data.map(({ assistsPerGame: _assistsPerGame, winsRatio, lossesRatio, ...row }) => ({
    ...row,
    id: randomUUID(),
    winsRatio: winsRatio.toString(),
    lossesRatio: lossesRatio.toString(),
  }));

  await db.delete(legacyPlayerCareerStats);
  await db.insert(legacyPlayerCareerStats).values(rows);

  console.log(`[done] Inserted ${data.length} legacy career stats rows`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("[error] Seeding failed:", err);
    process.exit(1);
  });